import {getCurrentYearStringPattern, getPriorYearStringPattern} from '../../fixtures/testsHelper'
/* eslint-disable max-len */

describe('Adjustments Page', () => {
    it('Default', () => {
        cy.get('@contentJSON').then((content) => {
            cy.aboutYouPage('single')
            cy.incomePage('salary', 'allYear', 'monthly', '6000', '60000', '1000', '10000')
            cy.get('[for="adjustments"]').should('have.text', getCurrentYearStringPattern(content.adjustments.adjustmentsLabel, 'cYYYY')).and('be.visible')
            cy.get('[data-testid="total"]').should('have.text', content.adjustments.total).and('be.visible')
            cy.get('[data-testid="nextButton"]').should('have.text', content.nextButton).and('be.enabled').and('be.visible')
            cy.get('[data-testid="backButton"]').should('have.text', content.backButton).and('be.enabled').and('be.visible')
        })
    })
    it('Completed', () => {
        cy.get('@contentJSON').then((content) => {
           cy.aboutYouPage('single')
           cy.incomePage('salary', 'allYear', 'monthly', '6000', '60000', '1000', '10000')
           cy.get('[data-testid="nextButton"]').should('have.text', content.nextButton).and('be.enabled').and('be.visible')
           cy.get('[data-testid="backButton"]').should('have.text', content.backButton).and('be.enabled').and('be.visible')
        })
     })
    it('All Checkboxes', () => {
         cy.get('@contentJSON').then((content) => {
            cy.aboutYouPage('single')
            cy.incomePage('salary', 'allYear', 'monthly', '6000', '60000', '1000', '10000')
            cy.get(':nth-child(1) > .mt-1 > .flex > .MuiFormControlLabel-root > .ml-3').should('have.text', content.adjustments.studentLoan).and('be.visible').click()
            cy.get('[data-testid="studentLoan-callout"]').should('have.text', content.adjustments.studentLoancallout).and('be.visible')
            cy.get('[data-testid=studentLoan0-label]').should('have.text', content.adjustments.requiredEnterAmount).and('be.visible')
            cy.get('[data-testid="studentLoan0-input"]').type('999999999').should('have.value', '$999,999,999').clear()
            cy.get('[data-testid="studentLoan0-input"]').type('hi$,()3000').should('have.value', '$3,000')
            cy.get('[data-testid="total"]').should('have.text', 'Adjustments entered: $3,000').and('be.visible').click()
            // Student Loan Box 2
            cy.get('[data-testid="addAnother-studentLoan"]').should('have.text', content.addAnotherButton).click()
            cy.get('[data-testid="studentLoan1-label"]').should('have.text', content.adjustments.enterAmount).and('be.visible')
            cy.get('[data-testid="deleteButton1"]').should('be.visible')
            cy.get('[data-testid="studentLoan1-input"]').type('999999999').should('have.value', '$999,999,999').clear()
            cy.get('[data-testid="studentLoan1-input"]').type('hi$,()3000').should('have.value', '$3,000')
            cy.get('[data-testid="total"]').should('have.text', 'Adjustments entered: $6,000').and('be.visible').click()
            // Student Loan Box 3
            cy.get('[data-testid="addAnother-studentLoan"]').should('have.text', content.addAnotherButton).click()
            cy.get('[data-testid="studentLoan2-label"]').should('have.text', content.adjustments.enterAmount).and('be.visible')
            cy.get('[data-testid="deleteButton2"]').should('be.visible')
            cy.get('[data-testid="studentLoan2-input"]').type('999999999').should('have.value', '$999,999,999').clear()
            cy.get('[data-testid="studentLoan2-input"]').type('hi$,()3000').should('have.value', '$3,000')
            cy.get('[data-testid="total"]').should('have.text', 'Adjustments entered: $9,000').and('be.visible').click()
            // Student Loan Box 4
            cy.get('[data-testid="addAnother-studentLoan"]').should('have.text', content.addAnotherButton).click()
            cy.get('[data-testid="studentLoan3-label"]').should('have.text', content.adjustments.enterAmount).and('be.visible')
            cy.get('[data-testid="deleteButton3"]').should('be.visible')
            cy.get('[data-testid="studentLoan3-input"]').type('999999999').should('have.value', '$999,999,999').clear()
            cy.get('[data-testid="studentLoan3-input"]').type('hi$,()3000').should('have.value', '$3,000')
            cy.get('[data-testid="total"]').should('have.text', 'Adjustments entered: $12,000').and('be.visible').click()
            cy.get('[data-testid="addAnother-studentLoan"]').should('have.text', content.addAnotherButton).and('be.visible').and('be.disabled')
            // Student Loan Box 3 Delete
            cy.get('[data-testid="studentLoan3-input"]').type('{backspace}{backspace}{backspace}{backspace}')
            cy.get('[data-testid="total"]').should('have.text', 'Adjustments entered: $9,000').and('be.visible').click()
            cy.get('[data-testid="deleteButton2"]').click()
            cy.get('[data-testid="total"]').should('have.text', 'Adjustments entered: $6,000').and('be.visible').click()
            // Educator Expense Deduction
             cy.get(':nth-child(2) > .mt-1 > .flex > .MuiFormControlLabel-root > .ml-3').should('have.text', content.adjustments.educator).and('be.visible').click()
             cy.get('[data-testid="educator-callout"]').should('have.text', content.adjustments.educatorcallout).and('be.visible')
             cy.get('[data-testid="educator0-label"]').should('have.text', content.adjustments.requiredEnterAmount).and('be.visible')
             cy.get('[data-testid="addAnother-educator"]').should('have.text', content.addAnotherButton).and('be.visible')
             cy.get('[data-testid="educator0-input"]').type('hi$,()1000').should('have.value', '$1,000')
             cy.get('[data-testid="total"]').should('have.text', 'Adjustments entered: $7,000').and('be.visible').click()
            // Deduction for contributions to an IRA
              cy.get(':nth-child(3) > .mt-1 > .flex > .MuiFormControlLabel-root > .ml-3').should('have.text', content.adjustments.ira).and('be.visible').click()
              cy.get('[data-testid="ira0-label"]').should('have.text', content.adjustments.requiredEnterAmount).and('be.visible')
              cy.get('[data-testid="addAnother-ira"]').should('have.text', content.addAnotherButton).and('be.visible')
              cy.get('[data-testid="ira0-input"]').type('hi$,()1,000').should('have.value', '$1,000')
              cy.get('[data-testid="total"]').should('have.text', 'Adjustments entered: $8,000').and('be.visible').click()
            // Health Savings Account Deduction
             cy.get(':nth-child(4) > .mt-1 > .flex > .MuiFormControlLabel-root > .ml-3').should('have.text', content.adjustments.hsa).and('be.visible').click()
             cy.get('[data-testid="hsa0-label"]').should('have.text', content.adjustments.requiredEnterAmount).and('be.visible')
             cy.get('[data-testid="addAnother-hsa"]').should('have.text', content.addAnotherButton).and('be.visible')
             cy.get('[data-testid="hsa0-input"]').type('1,000').should('have.value', '$1,000')
             cy.get('[data-testid="total"]').should('have.text', 'Adjustments entered: $9,000').and('be.visible').click()
            // Moving Expenses for Members of the Armed Services
             cy.get(':nth-child(5) > .mt-1 > .flex > .MuiFormControlLabel-root > .ml-3').should('have.text', content.adjustments.moving).and('be.visible').click()
            // cy.get('[data-testid=moving] > .MuiButtonBase-root').click()
             cy.get('[data-testid="moving0-label"]').should('have.text', content.adjustments.requiredEnterAmount).and('be.visible')
             cy.get('[data-testid="addAnother-moving"]').should('have.text', content.addAnotherButton).and('be.visible')
             cy.get('[data-testid="moving0-input"]').type('1,000').should('have.value', '$1,000')
             cy.get('[data-testid="total"]').should('have.text', 'Adjustments entered: $10,000').and('be.visible').click()
            // Alimony paid
             cy.get(':nth-child(6) > .mt-1 > .flex > .MuiFormControlLabel-root > .ml-3').should('have.text', content.adjustments.alimony).and('be.visible').click()
             cy.get('[data-testid="alimony0-label"]').should('have.text', content.adjustments.requiredEnterAmount).and('be.visible')
             cy.get('[data-testid="addAnother-alimony"]').should('have.text', content.addAnotherButton).and('be.visible')
             cy.get('[data-testid="alimony0-input"]').type('1,000').should('have.value', '$1,000')
             cy.get('[data-testid="total"]').should('have.text', 'Adjustments entered: $11,000').and('be.visible').click()
            // Penalty for Early Withdrawl of Savings
             cy.get(':nth-child(7) > .mt-1 > .flex > .MuiFormControlLabel-root > .ml-3').should('have.text', content.adjustments.earlyWithdrawal).and('be.visible').click()
             cy.get('[data-testid="earlyWithdrawal0-label"]').should('have.text', content.adjustments.requiredEnterAmount).and('be.visible')
             cy.get('[data-testid="addAnother-earlyWithdrawal"]').should('have.text', content.addAnotherButton).and('be.visible')
             cy.get('[data-testid="earlyWithdrawal0-input"]').type('1,000').should('have.value', '$1,000')
             cy.get('[data-testid="total"]').should('have.text', 'Adjustments entered: $12,000').and('be.visible').click()
            // Certain business credits for reserviys, performing artists, and fee-based gvernment officials
             cy.get(':nth-child(8) > .mt-1 > .flex > .MuiFormControlLabel-root > .ml-3').should('have.text', content.adjustments.business).and('be.visible').click()
             cy.get('[data-testid="business0-label"]').should('have.text', content.adjustments.requiredEnterAmount).and('be.visible')
             cy.get('[data-testid="addAnother-business"]').should('have.text', content.addAnotherButton).and('be.visible')
             cy.get('[data-testid="business0-input"]').type('1,000').should('have.value', '$1,000')
             cy.get('[data-testid="total"]').should('have.text', 'Adjustments entered: $13,000').and('be.visible')
         })
     })
     it('Adjustment Tooltips', () => {
        cy.get('@contentJSON').then((content) => {
           cy.aboutYouPage('single')
           cy.incomePage('salary', 'allYear', 'monthly', '6000', '60000', '1000', '10000')
           cy.get('[type="checkbox"]').check({ force: true })
           cy.get('[data-testid=studentLoan-helpTip] > .svg-inline--fa').click()
           cy.get('[data-testid=educator-helpTip] > .svg-inline--fa').click()
           cy.get('[data-testid=ira-helpTip] > .svg-inline--fa').click()
           cy.get('[data-testid=hsa-helpTip] > .svg-inline--fa').click()
           cy.get('[data-testid=moving-helpTip] > .svg-inline--fa').click()
           cy.get('[data-testid=alimony-helpTip] > .svg-inline--fa').click()
           cy.get('[data-testid=earlyWithdrawal-helpTip] > .svg-inline--fa').click()
           cy.get('[data-testid=business-helpTip] > .svg-inline--fa').click()
           cy.get('[data-testid=studentLoanToolTipHeading1]').should('have.text', content.adjustments.studentLoanToolTipHeading1).and('be.visible')
           cy.get('[data-testid=studentLoanToolTipParagraph1]').should('have.text', content.adjustments.studentLoanToolTipParagraph1).and('be.visible')
           cy.get('[data-testid=educatorToolTipHeading1]').should('have.text', content.adjustments.educatorToolTipHeading1).and('be.visible')
           cy.get('[data-testid=educatorToolTipParagraph1]').should('have.text', content.adjustments.educatorToolTipParagraph1).and('be.visible')
           cy.get('[data-testid=iraToolTipHeading1]').should('have.text', content.adjustments.iraToolTipHeading1).and('be.visible')
           cy.get('[data-testid=iraToolTipParagraph1]').should('have.text', content.adjustments.iraToolTipParagraph1).and('be.visible')
           cy.get('[data-testid=hsaToolTipHeading1]').should('have.text', content.adjustments.hsaToolTipHeading1).and('be.visible')
           cy.get('[data-testid=hsaToolTipParagraph1]').should('have.text', content.adjustments.hsaToolTipParagraph1).and('be.visible')
           cy.get('[data-testid=movingToolTipHeading1]').should('have.text', content.adjustments.movingToolTipHeading1).and('be.visible')
           cy.get('[data-testid=movingToolTipParagraph1]').should('have.text', content.adjustments.movingToolTipParagraph1).and('be.visible')
           cy.get('[data-testid=alimonyToolTipHeading1]').should('have.text', content.adjustments.alimonyToolTipHeading1).and('be.visible')
           cy.get('[data-testid=alimonyToolTipParagraph1]').should('have.text', content.adjustments.alimonyToolTipParagraph1).and('be.visible')
           cy.get('[data-testid=alimonyToolTipParagraph2]').should('have.text', getCurrentYearStringPattern(getPriorYearStringPattern(content.adjustments.alimonyToolTipParagraph2, 'pYYYY'),'cYYYY')).and('be.visible')
           cy.get('[data-testid=earlyWithdrawalToolTipHeading1]').should('have.text', content.adjustments.earlyWithdrawalToolTipHeading1).and('be.visible')
           cy.get('[data-testid=earlyWithdrawalToolTipParagraph1]').should('have.text', content.adjustments.earlyWithdrawalToolTipParagraph1).and('be.visible')
           cy.get('[data-testid=businessToolTipHeading1]').should('have.text', content.adjustments.businessToolTipHeading1).and('be.visible')
           cy.get('[data-testid=businessToolTipParagraph1]').should('have.text', content.adjustments.businessToolTipParagraph1).and('be.visible')
           cy.get('[data-testid=businessToolTipParagraph2]').should('have.text', content.adjustments.businessToolTipParagraph2).and('be.visible')
        })
    })
    //No more errors on nested checkboxes
    // it('Error Messages', () => {
    //     cy.get('@contentJSON').then((content) => {
    //         cy.aboutYouPage('single')
    //         cy.incomePage('salary', 'allYear', 'monthly', '6000', '60000', '1000', '10000')
    //         cy.get('[type="checkbox"]').check({ force: true })
    //         cy.get('[data-testid=nextButton]').click()
    //         cy.get('[data-testid=errorHeading]').should('have.text', 'The following 8 errors have occurred:')
    //     })
    // })
})
