/* eslint-disable max-len */
const content = require('../../fixtures/content.json')

describe('Global Test', () => {
    it('Footer', () => {
        cy.viewport(1280, 1024)
        cy.get('[data-testid="Our Agency"]').scrollIntoView().should('have.text', content.global.footer.ourAgency).and('be.visible')
        cy.get('[data-testid="aboutIrsLink"]').should('have.text', content.global.footer.aboutIRS).and('have.attr', 'href', content.global.footerLinks.aboutIRSLink).and('be.visible')
        cy.get('[data-testid="jobsLink"]').should('have.text', content.global.footer.workAtIRS).and('have.attr', 'href', content.global.footerLinks.workAtIRSLink).and('be.visible')
        cy.get('[data-testid="operationsAndBudgetLink"]').should('have.text', content.global.footer.operationsAndBudget).and('have.attr', 'href', content.global.footerLinks.operationsAndBudgetLink).and('be.visible')
        cy.get('[data-testid="helpLinkFooter"]').should('have.text', content.global.footer.helpFooter).and('have.attr', 'href', content.global.footerLinks.helpFooterLink).and('be.visible')
        cy.get('[data-testid="contectLink"]').should('have.text', content.global.footer.contactYourLocalOffice).and('have.attr', 'href', content.global.footerLinks.contactYourLocalOfficeLink).and('be.visible')
        cy.get('[data-testid="statsLink"]').should('have.text', content.global.footer.taxStatsFactsFigures).and('have.attr', 'href', content.global.footerLinks.taxStatsFactsFiguresLink).and('be.visible')
        cy.get('[data-testid="Know Your Rights"]').should('have.text', content.global.footer.knowYourRights).and('be.visible')
        cy.get('[data-testid="taxBORLink"]').should('have.text', content.global.footer.taxpayerBillOfRights).and('have.attr', 'href', content.global.footerLinks.taxpayerBillOfRightsLink).and('be.visible')
        cy.get('[data-testid="taxAdvocateLink"]').should('have.text', content.global.footer.taxpayerAdvocateService).and('have.attr', 'href', content.global.footerLinks.taxpayerAdvocateServiceLink).and('be.visible')
        cy.get('[data-testid="civilRightsLink"]').should('have.text', content.global.footer.civilRights).and('have.attr', 'href', content.global.footerLinks.civilRightsLink).and('be.visible')
        cy.get('[data-testid="freedomInfoActLink"]').should('have.text', content.global.footer.freedomInformationAct).and('have.attr', 'href', content.global.footerLinks.freedomInformationActLink).and('be.visible')
        cy.get('[data-testid="noFearLink"]').should('have.text', content.global.footer.noFearAct).and('have.attr', 'href', content.global.footerLinks.noFearActLink).and('be.visible')
        cy.get('[data-testid="noFearLink"] > svg').should('have.attr', 'data-testid', 'externalLink').and('be.visible')
        cy.get('[data-testid="Resolve an Issue"]').should('have.text', content.global.footer.resolveAnIssue).and('be.visible')
        cy.get('[data-testid="respondNoticeLink"]').should('have.text', content.global.footer.respondToANotice).and('have.attr', 'href', content.global.footerLinks.respondToANoticeLink).and('be.visible')
        cy.get('[data-testid="appealsLink"]').should('have.text', content.global.footer.independentOfficeOfAppeals).and('have.attr', 'href', content.global.footerLinks.independentOfficeOfAppealsLink).and('be.visible')
        cy.get('[data-testid="identityTheftLink"]').should('have.text', content.global.footer.identifyTheftProtection).and('have.attr', 'href', content.global.footerLinks.identifyTheftProtectionLink).and('be.visible')
        cy.get('[data-testid="phisingLink"]').should('have.text', content.global.footer.reportPhishing).and('have.attr', 'href', content.global.footerLinks.reportPhishingLink).and('be.visible')
        cy.get('[data-testid="taxFraudLink"]').should('have.text', content.global.footer.taxFraudAbuse).and('have.attr', 'href', content.global.footerLinks.taxFraudAbuseLink).and('be.visible')
        cy.get('[data-testid="criminalInvestigationLink"]').should('have.text', content.global.footer.criminalInvestigation).and('have.attr', 'href', content.global.footerLinks.criminalInvestigationLink).and('be.visible')
        cy.get('[data-testid="Languages"]').should('have.text', content.global.footer.languages).and('be.visible')
        cy.get('[data-testid="spanishLinkFooter"]').should('have.text', content.global.footer.spanish).and('have.attr', 'href', content.global.footerLinks.spanishLink).and('be.visible')
        cy.get('[data-testid="chineseSimplifiedLinkfooter"]').should('have.text', content.global.footer.chineseSimple).and('have.attr', 'href', content.global.footerLinks.chineseSimpleLink).and('be.visible')
        cy.get('[data-testid="chineseTraditionalLinkfooter"]').should('have.text', content.global.footer.chineseTraditional).and('have.attr', 'href', content.global.footerLinks.chineseTraditionalLink).and('be.visible')
        cy.get('[data-testid="koreanLinkFooter"]').should('have.text', content.global.footer.korean).and('have.attr', 'href', content.global.footerLinks.koreanLink).and('be.visible')
        cy.get('[data-testid="russianLinkFooter"]').should('have.text', content.global.footer.russian).and('have.attr', 'href', content.global.footerLinks.russianLink).and('be.visible')
        cy.get('[data-testid="kreyolLinkFooter"]').should('have.text', content.global.footer.haitian).and('have.attr', 'href', content.global.footerLinks.haitianLink).and('be.visible')
        cy.get('[data-testid="otherLanguagesLinkFooter"]').should('have.text', content.global.footer.otherLanguages).and('have.attr', 'href', content.global.footerLinks.otherLanguagesLink).and('be.visible')
        cy.get('[data-testid="vietnameseLinkFooter"]').should('have.text', content.global.footer.vietnamese).and('have.attr', 'href', content.global.footerLinks.vietnameseLink).and('be.visible')
        cy.get('[data-testid="englishLinkFooter"]').should('have.text', content.global.footer.english).and('have.attr', 'href', content.global.footerLinks.englishLink).and('be.visible')
        cy.get('[data-testid="Related Sites"]').should('have.text', content.global.footer.relatedSites).and('be.visible')
        cy.get('[data-testid="treasuryLink"]').should('have.text', content.global.footer.usTreasury).and('have.attr', 'href', content.global.footerLinks.usTreasuryLink).and('be.visible')
        cy.get('[data-testid="treasuryLink"] > svg').should('have.attr', 'data-testid', 'externalLink').and('be.visible')
        cy.get('[data-testid="treasInspLink"]').should('have.text', content.global.footer.treasuryInspectorGeneral).and('have.attr', 'href', content.global.footerLinks.treasuryInspectorGeneralLink).and('be.visible')
        cy.get('[data-testid="treasInspLink"] > svg').should('have.attr', 'data-testid', 'externalLink').and('be.visible')
        cy.get('[data-testid="usaGovLink"]').should('have.text', content.global.footer.usaGov).and('have.attr', 'href', content.global.footerLinks.usaGovLink).and('be.visible')
        cy.get('[data-testid="usaGovLink"] > svg').should('have.attr', 'data-testid', 'externalLink').and('be.visible')
        cy.get('[data-testid="usaSpendingGovLink"]').should('have.text', content.global.footer.usaSpendingGov).and('have.attr', 'href', content.global.footerLinks.usaSpendingGovLink).and('be.visible')
        cy.get('[data-testid="usaSpendingGovLink"] > svg').should('have.attr', 'data-testid', 'externalLink').and('be.visible')
        cy.get('[data-testid="facebookIcon"]').should('have.attr', 'href', content.global.footerLinks.facebookIconLink).and('be.visible')
        cy.get('[data-testid="twitterIcon"]').should('have.attr', 'href', content.global.footerLinks.twitterIconLink).and('be.visible')
        cy.get('[data-testid="instagramIcon"]').should('have.attr', 'href', content.global.footerLinks.instagramIconLink).and('be.visible')
        cy.get('[data-testid="linkedinIcon"]').should('have.attr', 'href', content.global.footerLinks.linkedinIconLink).and('be.visible')
        cy.get('[data-testid="youtubeIcon"]').should('have.attr', 'href', content.global.footerLinks.youtubeIconLink).and('be.visible')
        cy.get('[data-testid="irsAppIcon"]').should('have.attr', 'href', content.global.footerLinks.irsAppIconLink).and('be.visible')
        cy.get('[data-testid="footerLogo"]').should('have.attr', 'href', content.global.footerLinks.footerLogoLink).and('be.visible')
        cy.get('[data-testid="privacyLink"]').should('have.text', content.global.footer.privacyPolicy).and('have.attr', 'href', content.global.footerLinks.privacyPolicyLink).and('be.visible')
        cy.get('[data-testid="accessibilityLink"]').should('have.text', content.global.footer.accessibility).and('have.attr', 'href', content.global.footerLinks.accessibilityLink).and('be.visible')
    })
})
