/* eslint-disable newline-per-chained-call */
/* eslint-disable max-len */
const content = require('../../fixtures/content.json')

const searchText = '1040'
const device = 'iphone-x'

describe('Global Test', () => {
    it('Mobile Header', () => {
        cy.viewport(device)
        cy.get('[data-testid="irsgovLink"]').should('have.text', content.global.header.irsLogo).and('have.attr', 'href', content.global.headerLink.irsLogoLink).and('be.visible')
        cy.get('[data-testid="IRSLogo"]').should('be.visible')
        // Search Funtionality
        cy.get('#toggleSearch').click()
        cy.get('[data-testid="searchIcon"]').should('be.visible')
        cy.get('#headerSearchForm > [data-testid=searchField]').should('be.visible').type(searchText).should('have.value', searchText).and('be.visible')
        cy.get('#headerSearchForm').should('have.attr', 'target', '_blank').and('have.attr', 'action', content.global.headerLink.searchLink).and('have.attr', 'method', 'GET')
        cy.get('[data-testid="helpLinkMobile"]').should('have.text', content.global.header.help).and('have.attr', 'href', content.global.headerLink.helpLink).and('be.visible')
        // MegaMenu
        cy.get('[data-testid="mobileMenu"]').click()
        cy.get('[data-testid="newsLink"]').should('have.text', content.global.header.news).and('have.attr', 'href', content.global.headerLink.newsLink).and('be.visible')
        cy.get('[data-testid="charitiesLink"]').should('have.text', content.global.header.charities).and('have.attr', 'href', content.global.headerLink.charitiesLink).and('be.visible')
        cy.get('[data-testid="taxProsLink"]').should('have.text', content.global.header.taxPros).and('have.attr', 'href', content.global.headerLink.taxProsLink).and('be.visible')
        // Language switcher
        cy.get('#navLangButton').should('be.visible').click({ force: true })
        cy.get('[data-testid="spanishLinkHeaderMobile"]').last().should('have.text', content.global.languageSwitcher.spanish).and('have.attr', 'href', content.global.languageSwitcher.spanishLink).click({ force: true })
        cy.get('[data-testid="helpLinkMobile"]').should('have.text', content.global.languageSwitcher.spanishHelpLink).and('be.visible')
        cy.get('#untranslatedWarning').should('have.text', content.global.languageSwitcher.spanishUntranslated).and('be.visible')
        cy.get('#navLangButton').should('be.visible').click({ force: true })
        cy.get('[data-testid="chinese1LinkHeaderMobile"]').last().should('have.text', content.global.languageSwitcher.chinese1).and('have.attr', 'href', content.global.languageSwitcher.chinese1Link).click()
        cy.get('[data-testid="helpLinkMobile"]').should('have.text', content.global.languageSwitcher.chinese1HelpLink).and('be.visible')
        cy.get('#untranslatedWarning').should('have.text', content.global.languageSwitcher.chinese1Untranslated).and('be.visible')
        cy.get('#navLangButton').should('be.visible').click({ force: true })
        cy.get('[data-testid="chinese2LinkHeaderMobile"]').last().should('have.text', content.global.languageSwitcher.chinese2).and('have.attr', 'href', content.global.languageSwitcher.chinese2Link).click()
        cy.get('[data-testid="helpLinkMobile"]').should('have.text', content.global.languageSwitcher.chinese2HelpLink).and('be.visible')
        cy.get('#untranslatedWarning').should('have.text', content.global.languageSwitcher.chinese2Untranslated).and('be.visible')
        cy.get('#navLangButton').should('be.visible').click({ force: true })
        cy.get('[data-testid="koreanLinkHeaderMobile"]').last().should('have.text', content.global.languageSwitcher.korean).and('have.attr', 'href', content.global.languageSwitcher.koreanLink).click()
        cy.get('[data-testid="helpLinkMobile"]').should('have.text', content.global.languageSwitcher.koreanHelpLink).and('be.visible')
        cy.get('#untranslatedWarning').should('have.text', content.global.languageSwitcher.koreanUntranslated).and('be.visible')
        cy.get('#navLangButton').should('be.visible').click({ force: true })
        cy.get('[data-testid="russianLinkHeaderMobile"]').last().should('have.text', content.global.languageSwitcher.russian).and('have.attr', 'href', content.global.languageSwitcher.russianLink).click()
        cy.get('[data-testid="helpLinkMobile"]').should('have.text', content.global.languageSwitcher.russianHelpLink).and('be.visible')
        cy.get('#untranslatedWarning').should('have.text', content.global.languageSwitcher.russianUntranslated).and('be.visible')
        cy.get('#navLangButton').should('be.visible').click({ force: true })
        cy.get('[data-testid="vietnameseLinkHeaderMobile"]').last().should('have.text', content.global.languageSwitcher.vietnamese).and('have.attr', 'href', content.global.languageSwitcher.vietnameseLink).click()
        cy.get('[data-testid="helpLinkMobile"]').should('have.text', content.global.languageSwitcher.vietnameseHelpLink).and('be.visible')
        cy.get('#untranslatedWarning').should('have.text', content.global.languageSwitcher.vietnameseUntranslated).and('be.visible')
        cy.get('#navLangButton').should('be.visible').click({ force: true })
        cy.get('[data-testid="haitianLinkHeaderMobile"]').last().should('have.text', content.global.languageSwitcher.haitian).and('have.attr', 'href', content.global.languageSwitcher.haitianLink).click()
        cy.get('[data-testid="helpLinkMobile"]').should('have.text', content.global.languageSwitcher.haitianHelpLink).and('be.visible')
        cy.get('#untranslatedWarning').should('have.text', content.global.languageSwitcher.haitianUntranslated).and('be.visible')
        cy.get('#navLangButton').should('be.visible').click({ force: true })
        cy.get('[data-testid="englishLinkHeaderMobile"]').last().should('have.text', content.global.languageSwitcher.english).and('have.attr', 'href', content.global.languageSwitcher.englishLink).click()
        // File megamenu
        cy.get('[data-testid="fileLink"] > svg').should('be.visible')
        cy.get('[data-testid="fileLink"]').click({ force: true }).should('have.text', content.global.header.mobileFile).and('be.visible')
        cy.get('[data-testid="fileLink"] + div > div > div > a').should('have.text', content.global.header.mobileFileOverview).and('have.attr', 'href', content.global.headerLink.mobileFileOverviewLink).and('be.visible')
        cy.get('[data-testid="infoForTextFile"]').should('have.text', content.global.header.informationFor).and('be.visible')
        cy.get('[data-testid="individualsLinkMM"]').should('have.text', content.global.header.individuals).and('have.attr', 'href', content.global.headerLink.individualsLink).and('be.visible')
        cy.get('[data-testid="internationalLink"]').should('have.text', content.global.header.internationalTaxpayers).and('have.attr', 'href', content.global.headerLink.internationalTaxpayersLink).and('be.visible')
        cy.get('[data-testid="businessLink"]').should('have.text', content.global.header.businessSelfEmployed).and('have.attr', 'href', content.global.headerLink.businessSelfEmployedLink).and('be.visible')
        cy.get('[data-testid="governmentLink"]').should('have.text', content.global.header.govtEntities).and('have.attr', 'href', content.global.headerLink.govtEntitiesLink).and('be.visible')
        cy.get('[data-testid="filingForIndvText"]').should('have.text', content.global.header.filingForIndividuals).and('be.visible')
        cy.get('[data-testid="howToFileLink"]').should('have.text', content.global.header.howToFile).and('have.attr', 'href', content.global.headerLink.howToFileLink).and('be.visible')
        cy.get('[data-testid="whenToFileLink"]').should('have.text', content.global.header.whenToFile).and('have.attr', 'href', content.global.headerLink.whenToFileLink).and('be.visible')
        cy.get('[data-testid="whereToFileLink"]').should('have.text', content.global.header.whereToFile).and('have.attr', 'href', content.global.headerLink.whereToFileLink).and('be.visible')
        cy.get('[data-testid="updateMyInfoLink"]').should('have.text', content.global.header.updateInformation).and('have.attr', 'href', content.global.headerLink.updateInformationLink).and('be.visible')
        cy.get('[data-testid="popularTextFile"]').should('have.text', content.global.header.popular).and('be.visible')
        cy.get('[data-testid="economicImpactLink"]').should('have.text', content.global.header.economicImpact).and('have.attr', 'href', content.global.headerLink.economicImpactLink).and('be.visible')
        cy.get('[data-testid="coronavirusLink"]').should('have.text', content.global.header.coronavirus).and('have.attr', 'href', content.global.headerLink.coronavirusLink).and('be.visible')
        cy.get('[data-testid="freeFileLink"]').should('have.text', content.global.header.freeFile).and('have.attr', 'href', content.global.headerLink.freeFileLink).and('be.visible')
        cy.get('[data-testid="taxRecordLink"]').should('have.text', content.global.header.taxRecord).and('have.attr', 'href', content.global.headerLink.taxRecordLink).and('be.visible')
        cy.get('[data-testid="ipPinLink"]').should('have.text', content.global.header.IPPIN).and('have.attr', 'href', content.global.headerLink.IPPINLink).and('be.visible')
        // Pay megamenu
        cy.get('[data-testid="payLink"] > svg').should('be.visible')
        cy.get('[data-testid="payLink"]').click({ force: true }).should('have.text', content.global.header.mobilePay).and('be.visible')
        cy.get('[data-testid="payLink"] + div > div > div > a').should('have.text', content.global.header.mobilePayOverview).and('have.attr', 'href', content.global.headerLink.mobilePayOverviewLink).and('be.visible')
        cy.get('[data-testid="payByText"]').should('have.text', content.global.header.payBy).and('be.visible')
        cy.get('[data-testid="bankAcctLink"]').should('have.text', content.global.header.backAccount).and('have.attr', 'href', content.global.headerLink.backAccountLink).and('be.visible')
        cy.get('[data-testid="debitCCLink"]').should('have.text', content.global.header.debitOrCreditCard).and('have.attr', 'href', content.global.headerLink.debitOrCreditCardLink).and('be.visible')
        cy.get('[data-testid="paymenPlanLink"]').should('have.text', content.global.header.paymentPlan).and('have.attr', 'href', content.global.headerLink.paymentPlanLink).and('be.visible')
        cy.get('[data-testid="eftpsLink"]').should('have.text', content.global.header.eftps).and('have.attr', 'href', content.global.headerLink.eftpsLink).and('be.visible')
        cy.get('[data-testid="popularTextPay"]').should('have.text', content.global.header.popular).and('be.visible')
        cy.get('[data-testid="viewyourAcctLink"]').should('have.text', content.global.header.viewYourAccount).and('have.attr', 'href', content.global.headerLink.viewYourAccountLink).and('be.visible')
        cy.get('[data-testid="tweLink"]').should('have.text', content.global.header.twe).and('have.attr', 'href', content.global.headerLink.tweLink).and('be.visible')
        cy.get('[data-testid="estimatedTaxesLink"]').should('have.text', content.global.header.estimatedTaxes).and('have.attr', 'href', content.global.headerLink.estimatedTaxesLink).and('be.visible')
        cy.get('[data-testid="penaltiesLink"]').should('have.text', content.global.header.penalties).and('have.attr', 'href', content.global.headerLink.penaltiesLink).and('be.visible')
        // Refunds megamenu
        cy.get('[data-testid="refundLink"] > svg').should('be.visible')
        cy.get('[data-testid="refundLink"]').click({ force: true }).should('have.text', content.global.header.mobileRefunds).and('be.visible')
        cy.get('[data-testid="refundLink"] + div > div > div > a').should('have.text', content.global.header.mobileRefundsOverview).and('have.attr', 'href', content.global.headerLink.mobileRefundsOverviewLink).and('be.visible')
        cy.get('[data-testid="whereMyRefundLink"]').should('have.text', content.global.header.wheresMyRefund).and('have.attr', 'href', content.global.headerLink.wheresMyRefundLink).and('be.visible')
        cy.get('[data-testid="whatToExpectLink"]').should('have.text', content.global.header.whatToExpect).and('have.attr', 'href', content.global.headerLink.whatToExpectLink).and('be.visible')
        cy.get('[data-testid="directDepositLink"]').should('have.text', content.global.header.directDeposit).and('have.attr', 'href', content.global.headerLink.directDepositLink).and('be.visible')
        cy.get('[data-testid="reducedRefundsLink"]').should('have.text', content.global.header.reducedRefunds).and('have.attr', 'href', content.global.headerLink.reducedRefundsLink).and('be.visible')
        cy.get('[data-testid="fixReturnLink"]').should('have.text', content.global.header.fixCorrectAReturn).and('have.attr', 'href', content.global.headerLink.fixCorrectAReturnLink).and('be.visible')
        // Credits & Deductions megamenu
        cy.get('[data-testid="creditsDeductionsLink"] > svg').should('be.visible')
        cy.get('[data-testid="creditsDeductionsLink"]').click({ force: true }).should('have.text', content.global.header.mobileCredits).and('be.visible')
        cy.get('[data-testid="creditsDeductionsLink"] + div > div > div > a').should('have.text', content.global.header.mobileCreditsOverview).and('have.attr', 'href', content.global.headerLink.mobileCreditsOverviewLink).and('be.visible')
        cy.get('[data-testid="infoForTextCD"]').should('have.text', content.global.header.informationCredits).and('be.visible')
        cy.get('[data-testid="youFamilyLink"]').should('have.text', content.global.header.individualsCredits).and('have.attr', 'href', content.global.headerLink.individualsCreditsLink).and('be.visible')
        cy.get('[data-testid="businessCredLink"]').should('have.text', content.global.header.businessSelfEmployedCredits).and('have.attr', 'href', content.global.headerLink.businessSelfEmployedCreditsLink).and('be.visible')
        cy.get('[data-testid="poularTextCD"]').should('have.text', content.global.header.popular).and('be.visible')
        cy.get('[data-testid="eitcLink"]').should('have.text', content.global.header.eitc).and('have.attr', 'href', content.global.headerLink.eitcLink).and('be.visible')
        cy.get('[data-testid="ctcLink"]').should('have.text', content.global.header.childTaxCredit).and('have.attr', 'href', content.global.headerLink.childTaxCreditLink).and('be.visible')
        cy.get('[data-testid="standardDedLink"]').should('have.text', content.global.header.standardDeduction).and('have.attr', 'href', content.global.headerLink.standardDeductionLink).and('be.visible')
        cy.get('[data-testid="healthCovgLink"]').should('have.text', content.global.header.healthCoverage).and('have.attr', 'href', content.global.headerLink.healthCoverageLink).and('be.visible')
        cy.get('[data-testid="retirementLink"]').should('have.text', content.global.header.retirementSavings).and('have.attr', 'href', content.global.headerLink.retirementSavingsLink).and('be.visible')
        // Forms megamenu
        cy.get('[data-testid="formsInsLink"] > svg').should('be.visible')
        cy.get('[data-testid="formsInsLink"]').click({ force: true }).should('have.text', content.global.header.mobileForms).and('be.visible')
        cy.get('[data-testid="formsInsLink"] + div > div > div > a').should('have.text', content.global.header.mobileFormsOverview).and('have.attr', 'href', content.global.headerLink.mobileFormsOverviewLink).and('be.visible')
        cy.get('[data-testid="formsInsText"]').should('have.text', content.global.header.formsAndInstructions).and('be.visible')
        cy.get('[data-testid="1040Link"]').should('have.text', content.global.header.form1040).and('have.attr', 'href', content.global.headerLink.form1040Link).and('be.visible')
        cy.get('[data-testid="1040iLink"]').should('have.text', content.global.header.form1040Instructions).and('have.attr', 'href', content.global.headerLink.form1040InstructionsLink).and('be.visible')
        cy.get('[data-testid="w9Link"]').should('have.text', content.global.header.formW9).and('have.attr', 'href', content.global.headerLink.formW9Link).and('be.visible')
        cy.get('[data-testid="4506tLink"]').should('have.text', content.global.header.form4506T).and('have.attr', 'href', content.global.headerLink.form4506TLink).and('be.visible')
        cy.get('[data-testid="w4Link"]').should('have.text', content.global.header.formW4).and('have.attr', 'href', content.global.headerLink.formW4Link).and('be.visible')
        cy.get('[data-testid="941Link"]').should('have.text', content.global.header.form941).and('have.attr', 'href', content.global.headerLink.form941Link).and('be.visible')
        cy.get('[data-testid="w2Link"]').should('have.text', content.global.header.formW2).and('have.attr', 'href', content.global.headerLink.formW2Link).and('be.visible')
        cy.get('[data-testid="9465Link"]').should('have.text', content.global.header.form9465).and('have.attr', 'href', content.global.headerLink.form9465Link).and('be.visible')
        cy.get('[data-testid="popularTaxProsText"]').should('have.text', content.global.header.popularForms).and('be.visible')
        cy.get('[data-testid="1040xLink"]').should('have.text', content.global.header.form1040X).and('have.attr', 'href', content.global.headerLink.form1040XLink).and('be.visible')
        cy.get('[data-testid="2848Link"]').should('have.text', content.global.header.form2848).and('have.attr', 'href', content.global.headerLink.form2848Link).and('be.visible')
        cy.get('[data-testid="w7Link"]').should('have.text', content.global.header.formW7).and('have.attr', 'href', content.global.headerLink.formW7Link).and('be.visible')
        cy.get('[data-testid="230Link"]').should('have.text', content.global.header.circular230).and('have.attr', 'href', content.global.headerLink.circular230Link).and('be.visible')
    })
})
