const content = require('../../fixtures/content.json')

describe('Global Test', () => {
    it('Skip Ahead', () => {
        cy.get('[data-testid="stepIndicatorStep2"]').click()
        cy.get('[data-testid="incomeWithholdingTitle"]').should('have.text', content.incomeWithholding.title).and('be.visible')
        cy.get('[data-testid="warningHeading"]').should('have.text', content.error.skipAheadHeading).and('be.visible')
        cy.get('[data-testid="warningBody"]').should('have.text', content.error.skipAheadIncome).and('be.visible')
        cy.get('[data-testid="stepIndicatorStep3"]').click()
        cy.get('[data-testid="adjustmentsTitle"]').should('have.text', content.adjustments.adjustmentsTitle).and('be.visible')
        cy.get('[data-testid="warningHeading"]').should('have.text', content.error.skipAheadHeading).and('be.visible')
        cy.get('[data-testid="warningBody"]').should('have.text', content.error.skipAheadAdjustments).and('be.visible')
        cy.get('[data-testid="stepIndicatorStep4"]').click()
        cy.get('[data-testid="deductionsTitle"]').should('have.text', content.deductions.title).and('be.visible')
        cy.get('[data-testid="warningHeading"]').should('have.text', content.error.skipAheadHeading).and('be.visible')
        cy.get('[data-testid="warningBody"]').should('have.text', content.error.skipAheadDeductions).and('be.visible')
        cy.get('[data-testid="stepIndicatorStep5"]').click()
        cy.get('[data-testid="taxCreditsTitle"]').should('have.text', content.taxCredits.title).and('be.visible')
        cy.get('[data-testid="warningHeading"]').should('have.text', content.error.skipAheadHeading).and('be.visible')
        cy.get('[data-testid="warningBody"]').should('have.text', content.error.skipAheadTaxCredits).and('be.visible')
        cy.get('[data-testid="stepIndicatorStep6"]').click()
        //cy.get('[data-testid="resultsTitle"]').should('have.text', content.results.title).and('be.visible')
        cy.get('[data-testid="warningHeading"]').should('have.text', content.error.skipAheadHeading).and('be.visible')
        cy.get('[data-testid="warningBody"]').should('have.text', content.error.skipAheadResults).and('be.visible')
    })
})
